'use client';

import { useState } from 'react';
import { useAnalysisStore } from '@/store/analysisStore';
import { Cpu, Search, Brain, ShieldCheck, GitCommit, ArrowRightLeft } from 'lucide-react';

type AgentKey = 'supervisor' | 'research' | 'analysis' | 'critic';

interface AgentInfo {
  name: string;
  role: string;
  icon: any;
  color: string;
  activeColor: string;
  glowColor: string;
  description: string;
  capabilities: string[];
}

const AGENTS: Record<AgentKey, AgentInfo> = {
  supervisor: {
    name: 'Supervisor Agent',
    role: 'Orchestrator & Router',
    icon: Cpu,
    color: 'border-zinc-200 text-zinc-500 bg-white hover:border-zinc-300',
    activeColor: 'border-purple-500 text-purple-600 bg-purple-50/50 shadow-purple-100',
    glowColor: 'rgba(168, 85, 247, 0.4)',
    description: 'The central hub of the system. It inspects the current state of analysis, decides which agent needs to run next, handles routing logic, and tracks rejections/retries.',
    capabilities: [
      'State-based conditional routing',
      'Retry loop management (up to 5 retries)',
      'Token validation & session tracking',
      'Final verification gates closure'
    ]
  },
  research: {
    name: 'Research Agent',
    role: 'Information Gatherer',
    icon: Search,
    color: 'border-zinc-200 text-zinc-500 bg-white hover:border-zinc-300',
    activeColor: 'border-blue-500 text-blue-600 bg-blue-50/50 shadow-blue-100',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    description: 'Queries cosmetic ingredient databases and internet resources. Triage searches between the local Qdrant vector database (using Sentence-Transformer embeddings) and fallback Tavily web searches.',
    capabilities: [
      'AI-based nomenclature classification',
      'Vector semantic search (Qdrant Client)',
      'Tavily Advanced Web Search fallback',
      'Confidence scoring & retrieval logic'
    ]
  },
  analysis: {
    name: 'Analysis Agent',
    role: 'Safety & Custom Scorer',
    icon: Brain,
    color: 'border-zinc-200 text-zinc-500 bg-white hover:border-zinc-300',
    activeColor: 'border-emerald-500 text-emerald-600 bg-emerald-50/50 shadow-emerald-100',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    description: 'Runs personalized safety scoring and reports. It customizes ratings based on user skin type, flags user allergens, explains chemical mechanisms, and builds the safety analysis table.',
    capabilities: [
      'Gemini 2.5 Flash safety analysis',
      'Personalized skin type calibration',
      'Allergen cross-referencing & warning flags',
      'Dynamic markdown report generation'
    ]
  },
  critic: {
    name: 'Critic Agent',
    role: 'Quality & QA Validator',
    icon: ShieldCheck,
    color: 'border-zinc-200 text-zinc-500 bg-white hover:border-zinc-300',
    activeColor: 'border-amber-500 text-amber-600 bg-amber-50/50 shadow-amber-100',
    glowColor: 'rgba(245, 158, 11, 0.4)',
    description: 'Validates quality and completeness of reports generated by the Analysis Agent. If it rejects the analysis (due to missing details or unaddressed allergens), it loops back with structured feedback.',
    capabilities: [
      'Strict multi-gate validation',
      'Allergen flag enforcement validation',
      'Tone checking by user expertise level',
      'Feedback generation for Analysis retry'
    ]
  }
};

export default function AgentWorkflowDiagram() {
  const { progress, isAnalyzing } = useAnalysisStore();
  const [selectedAgent, setSelectedAgent] = useState<AgentKey>('supervisor');

  // Map progress stage to AgentKey
  const currentStage = progress?.stage?.toLowerCase() || '';
  const activeAgent: AgentKey | null = isAnalyzing
    ? currentStage.includes('research')
      ? 'research'
      : currentStage.includes('analysis')
      ? 'analysis'
      : currentStage.includes('critic')
      ? 'critic'
      : 'supervisor'
    : null;

  return (
    <div className="w-full max-w-4xl mx-auto bg-white p-6 rounded-xl shadow-md border border-zinc-200 space-y-6">
      <style dangerouslySetInnerHTML={{ __html: `
        @keyframes dash {
          to {
            stroke-dashoffset: -40;
          }
        }
        .animate-dash-active {
          stroke-dasharray: 8, 4;
          animation: dash 1.5s linear infinite;
        }
      `}} />

      <div>
        <h3 className="text-lg font-bold text-zinc-900 flex items-center gap-2">
          <ArrowRightLeft className="h-5 w-5 text-indigo-600" />
          Multi-Agent Orchestration Workflow
        </h3>
        <p className="text-zinc-500 text-xs mt-0.5">
          Our system runs a coordinated LangGraph workflow with specialized agents. Click any agent below to view its capabilities.
        </p>
      </div>

      {/* Visual Diagram */}
      <div className="relative w-full h-[320px] max-w-[620px] mx-auto border border-zinc-100 rounded-lg bg-zinc-50/40 overflow-hidden">
        {/* Connection Lines (SVG) */}
        <svg className="absolute inset-0 w-full h-full pointer-events-none" viewBox="0 0 600 320" fill="none">
          {/* Supervisor -> Research (Path 1) */}
          <path
            d="M 270 75 L 130 205"
            stroke={activeAgent === 'research' ? '#3b82f6' : '#e4e4e7'}
            strokeWidth={activeAgent === 'research' ? '2.5' : '1.5'}
            className={activeAgent === 'research' ? 'animate-dash-active' : ''}
            strokeDasharray="5,5"
          />
          {activeAgent === 'research' && (
            <text x="160" y="130" fill="#2563eb" className="text-[10px] font-bold fill-blue-600 bg-white" textAnchor="middle">
              1. Dispatch
            </text>
          )}

          {/* Research -> Analysis (Path 2) */}
          <path
            d="M 170 235 L 230 235"
            stroke={activeAgent === 'research' ? '#3b82f6' : activeAgent === 'analysis' ? '#10b981' : '#e4e4e7'}
            strokeWidth={activeAgent === 'research' || activeAgent === 'analysis' ? '2.5' : '1.5'}
            className={activeAgent === 'research' || activeAgent === 'analysis' ? 'animate-dash-active' : ''}
            strokeDasharray="5,5"
          />
          {(activeAgent === 'research' || activeAgent === 'analysis') && (
            <text x="200" y="225" fill="#10b981" className="text-[10px] font-bold fill-emerald-600" textAnchor="middle">
              2. Data
            </text>
          )}

          {/* Analysis -> Critic (Path 3) */}
          <path
            d="M 370 235 L 430 235"
            stroke={activeAgent === 'analysis' ? '#10b981' : activeAgent === 'critic' ? '#f59e0b' : '#e4e4e7'}
            strokeWidth={activeAgent === 'analysis' || activeAgent === 'critic' ? '2.5' : '1.5'}
            className={activeAgent === 'analysis' || activeAgent === 'critic' ? 'animate-dash-active' : ''}
            strokeDasharray="5,5"
          />
          {(activeAgent === 'analysis' || activeAgent === 'critic') && (
            <text x="400" y="225" fill="#d97706" className="text-[10px] font-bold fill-amber-600" textAnchor="middle">
              3. Report
            </text>
          )}

          {/* Critic -> Supervisor (Path 4) */}
          <path
            d="M 470 205 L 330 75"
            stroke={activeAgent === 'critic' ? '#f59e0b' : '#e4e4e7'}
            strokeWidth={activeAgent === 'critic' ? '2.5' : '1.5'}
            className={activeAgent === 'critic' ? 'animate-dash-active' : ''}
            strokeDasharray="5,5"
          />
          {activeAgent === 'critic' && (
            <text x="430" y="130" fill="#d97706" className="text-[10px] font-bold fill-amber-600" textAnchor="middle">
              4. Validation
            </text>
          )}

          {/* Critic -> Analysis (Retry Loop Path 5 - Curved) */}
          <path
            d="M 470 255 Q 300 315 130 255"
            stroke={isAnalyzing && currentStage.includes('critic_rejected') ? '#ef4444' : '#e4e4e7'}
            strokeWidth={isAnalyzing && currentStage.includes('critic_rejected') ? '2.5' : '1.5'}
            className={isAnalyzing && currentStage.includes('critic_rejected') ? 'animate-dash-active' : ''}
            strokeDasharray="5,5"
          />
          {isAnalyzing && currentStage.includes('critic_rejected') && (
            <text x="300" y="300" fill="#ef4444" className="text-[10px] font-bold fill-red-500" textAnchor="middle">
              🔄 Reject & Retry Loop (Feedback)
            </text>
          )}
        </svg>

        {/* Node: Supervisor */}
        <button
          onClick={() => setSelectedAgent('supervisor')}
          className={`absolute left-[50%] top-[60px] -translate-x-1/2 -translate-y-1/2 flex flex-col items-center p-3 rounded-xl border transition-all cursor-pointer select-none text-center w-[130px] ${
            activeAgent === 'supervisor' ? AGENTS.supervisor.activeColor : AGENTS.supervisor.color
          } ${selectedAgent === 'supervisor' ? 'ring-2 ring-indigo-500 ring-offset-2 shadow-sm' : ''}`}
          style={activeAgent === 'supervisor' ? { boxShadow: `0 0 15px ${AGENTS.supervisor.glowColor}` } : {}}
        >
          <Cpu className="h-5 w-5 mb-1 text-purple-600" />
          <span className="text-[11px] font-extrabold tracking-tight text-zinc-800">Supervisor</span>
          <span className="text-[9px] text-zinc-400 font-semibold leading-none mt-0.5">Orchestration</span>
        </button>

        {/* Node: Research */}
        <button
          onClick={() => setSelectedAgent('research')}
          className={`absolute left-[16.67%] top-[235px] -translate-x-1/2 -translate-y-1/2 flex flex-col items-center p-3 rounded-xl border transition-all cursor-pointer select-none text-center w-[130px] ${
            activeAgent === 'research' ? AGENTS.research.activeColor : AGENTS.research.color
          } ${selectedAgent === 'research' ? 'ring-2 ring-indigo-500 ring-offset-2 shadow-sm' : ''}`}
          style={activeAgent === 'research' ? { boxShadow: `0 0 15px ${AGENTS.research.glowColor}` } : {}}
        >
          <Search className="h-5 w-5 mb-1 text-blue-600" />
          <span className="text-[11px] font-extrabold tracking-tight text-zinc-800">Research Agent</span>
          <span className="text-[9px] text-zinc-400 font-semibold leading-none mt-0.5">Data Retrieval</span>
        </button>

        {/* Node: Analysis */}
        <button
          onClick={() => setSelectedAgent('analysis')}
          className={`absolute left-[50%] top-[235px] -translate-x-1/2 -translate-y-1/2 flex flex-col items-center p-3 rounded-xl border transition-all cursor-pointer select-none text-center w-[130px] ${
            activeAgent === 'analysis' ? AGENTS.analysis.activeColor : AGENTS.analysis.color
          } ${selectedAgent === 'analysis' ? 'ring-2 ring-indigo-500 ring-offset-2 shadow-sm' : ''}`}
          style={activeAgent === 'analysis' ? { boxShadow: `0 0 15px ${AGENTS.analysis.glowColor}` } : {}}
        >
          <Brain className="h-5 w-5 mb-1 text-emerald-600" />
          <span className="text-[11px] font-extrabold tracking-tight text-zinc-800">Analysis Agent</span>
          <span className="text-[9px] text-zinc-400 font-semibold leading-none mt-0.5">Report Writer</span>
        </button>

        {/* Node: Critic */}
        <button
          onClick={() => setSelectedAgent('critic')}
          className={`absolute left-[83.33%] top-[235px] -translate-x-1/2 -translate-y-1/2 flex flex-col items-center p-3 rounded-xl border transition-all cursor-pointer select-none text-center w-[130px] ${
            activeAgent === 'critic' ? AGENTS.critic.activeColor : AGENTS.critic.color
          } ${selectedAgent === 'critic' ? 'ring-2 ring-indigo-500 ring-offset-2 shadow-sm' : ''}`}
          style={activeAgent === 'critic' ? { boxShadow: `0 0 15px ${AGENTS.critic.glowColor}` } : {}}
        >
          <ShieldCheck className="h-5 w-5 mb-1 text-amber-500" />
          <span className="text-[11px] font-extrabold tracking-tight text-zinc-800">Critic Agent</span>
          <span className="text-[9px] text-zinc-400 font-semibold leading-none mt-0.5">QA & Verification</span>
        </button>
      </div>

      {/* Agent Detail Section */}
      <div className="bg-zinc-50 rounded-xl p-5 border border-zinc-200 transition-all duration-300">
        <div className="flex items-center gap-3 mb-3 pb-3 border-b border-zinc-200">
          <div className="p-2 rounded-lg bg-indigo-50 text-indigo-600">
            {(() => {
              const SelectedIcon = AGENTS[selectedAgent].icon;
              return <SelectedIcon className="h-5 w-5 animate-pulse" />;
            })()}
          </div>
          <div>
            <h4 className="font-extrabold text-zinc-950 text-sm leading-tight">
              {AGENTS[selectedAgent].name}
            </h4>
            <span className="text-[10px] uppercase tracking-wider font-extrabold text-indigo-600 bg-indigo-50 px-1.5 py-0.5 rounded-md mt-1 inline-block">
              {AGENTS[selectedAgent].role}
            </span>
          </div>
        </div>
        
        <p className="text-zinc-600 text-xs leading-relaxed mb-4">
          {AGENTS[selectedAgent].description}
        </p>
        
        <div className="space-y-2">
          <h5 className="text-[10px] font-bold uppercase tracking-wider text-zinc-400 font-mono">Core Capabilities:</h5>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            {AGENTS[selectedAgent].capabilities.map((capability, idx) => (
              <div key={idx} className="flex items-center gap-2 text-zinc-700 text-xs bg-white py-1.5 px-3 rounded-lg border border-zinc-100">
                <GitCommit className="h-3.5 w-3.5 text-indigo-500 shrink-0" />
                <span>{capability}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
